### ISSUE TITLE
MSSQL connector supports secure connection between Secretless and target service

### ISSUE THREAD

**Issue by doodlesbykumbi** [cyberark/secretless-broker#1005]
## Description
MSSQL connector supports configuring secure connection between Secretless and target service

AC:
- [ ] The security of communication between Secretless and the target service is configurable via Secretless configuration
- [ ] Secure connections between Secretless and the target service can be configured to require verification, similar to how mysql or postgres do but in a way appropriate to mssql

**Comment by izgeri** [comment]
Closed as duplicate of #1032
