### ISSUE TITLE
Address tech debt for MSSQL

### ISSUE THREAD

**Issue by doodlesbykumbi** [cyberark/secretless-broker#1006]
## Description

- [ ] MSSQL Connector faithfully propagates (appropriate within the context of Secretless) connection parameters from client to target service.
- [ ] MSSQL Connector faithfully propagates errors between client and target service.
- [ ] Verify the PRELOGIN response is created correctly 
- [ ] Test the OK message with different TDS versions and Server versions
- [ ] Build the OK message the way we do it PG
- [ ] Check if we can extract Login Ack response details

**Comment by izgeri** [comment]
The content of this ticket was moved to #1012, #1013, #1014, #1015, #1016, #1017
