### ISSUE TITLE
DUPLICATE: MSSQL connector can extract Login Ack response details

### ISSUE THREAD

**Issue by izgeri** [cyberark/secretless-broker#1015]
At present the connector sends a hard-coded OK response message to client.
(internal/plugin/connectors/tcp/mssql/authentication.go:62)

In general, the OK response contains information about the target service. It is, therefore, important for it to be dynamic and be derived from the actual login response from the target service.  

closed as duplicate

**Comment by izgeri** [comment]
@doodlesbykumbi can you please add more details to this one?

**Comment by doodlesbykumbi** [comment]
This is a duplicate
