### ISSUE TITLE
MSSQL connector has more complete integration tests

### ISSUE THREAD

**Issue by izgeri** [cyberark/secretless-broker#1023]
MSSQL has integration tests that validate:
- An app is able to connect to MSSQL via Secretless using:
  - correct username, wrong password
  - wrong username, wrong password
  - empty username, empty password
- An app is unable to connect to MSSQL via Secretless if Secretless is configured with the wrong credentials

**Comment by jonahx** [comment]
Superseded by:

https://app.zenhub.com/workspaces/secretless-5c9d073c270ed03f5cb98c95/issues/cyberark/secretless-broker/1039
