### ISSUE TITLE
We have evaluated whether the MSSQL connector supports session recovery and federated authentication

### ISSUE THREAD

**Issue by izgeri** [cyberark/secretless-broker#1086]
We don't yet know if the MSSQL connector supports "Session Recovery" and "Federated Authentication" (docs [here](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-tds/2eb82f8e-11f0-46dc-b42d-27302fa4701a)).  For the Session Recovery feature, what might be an issue is that this involves a Login/LoginAck exchange that's outside of the normal sequence that we expect, and it's not clear if our code is resilient to that. The Federated Authentication is probably a don't care, but we should take a look, decide, and document support vs. non-support.

**Comment by izgeri** [comment]
Note: re federated authentication
based on [these docs](https://docs.microsoft.com/en-us/sql/ssms/f1-help/connect-to-server-database-engine?view=sql-server-2017) it appears that federated authentication is only possible using an AD-based authentication mode. The connector only supports SQL Server authentication mode at this time, so I believe this is not relevant for us at this time.

**Comment by diverdane** [comment]
The "Session Restore" feature is one of the MSSQL/TDS "Feature Extensions" that can be negotiated as part of the Login/Login-Response exchange between MSSQL client and server. These feature extensions can be thought of as capabilities, and are documented in the [TDS Login7](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-tds/773a62b6-ee89-4c02-9e5e-344882630aac) and [TDS FEATUREEXTACK](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-tds/2eb82f8e-11f0-46dc-b42d-27302fa4701a) message/token documentation.

The intent of the Session Restore feature is to allow a client to reconnect and pick up "where it left off" e.g. after a network disconnect. The "where it left off" is still a bit vague to me. The way the feature works is that the server sends initial state to the client when the authenticated connection is first established, and then it continually sends Session State tokens containing state info whenever there are state changes. The client is expected to store this as context to be used for restoring a session if desired following a disconnect. 

Session State is defined [here](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-tds/626fbe19-f356-4599-ba17-c70f44005106). The vagueness comes in when you look at the definition of the StateValue field in the Session State token: "_**The value of the session state. This can be any arbitrary data as long as the server understands it.**_".

To add support for this feature, we would have to add some code to MSSQL secretless to:
- Parse the Feature Extension fields in Login requests from the client, and pass these to the server.
- Parse the Feature Extension Ack tokens in the login response from the server, and pass these to the client

Testing this feature would be complicated... The clients that we're already using for testing (sqlcmd and Kumbi's go-mssqldb based client) don't support this, as far as I can tell, so we'd be creating tests that would depend upon our interpretation (and implementation, on the client side) of the Microsoft specs.

I would recommend leaving this feature as unsupported, until/unless we have a customer asking for this feature and providing a good use case for Session Restore.

**Comment by diverdane** [comment]
![image.png](https://images.zenhubusercontent.com/5dcac57192830b0001efff9f/14f2bacc-7ed4-4524-8772-39bcda592942)

**Comment by izgeri** [comment]
thanks for looking into this @diverdane! I agree that we should leave this unexplored for now, given that there's not an easy path to validate how this might be used.

given that finding and the earlier finding that federated authentication doesn't need to be explored while we're only supporting SQL server authentication, I think we can close this card for now.
