### ISSUE TITLE
Permission denied on docs page

### ISSUE THREAD

**Issue by jcantosz** [cyberark/secretless-broker#1121]
## Summary
The documentation link on [secretless.io](https://secretless.io) yields the message "You do not have permission to view this directory or page." 

## Steps to Reproduce
1. Navigate to [secretless.io](https://secretless.io)
2. Click on the "Documentation" link and get redirected to [docs.secretless.io/Latest/en/](https://docs.secretless.io/Latest/en/)
3. See the error message "You do not have permission to view this directory or page."

## Expected Results
The documentation page for the secreless-broker

## Actual Results (including error logs, if applicable)
A 403 on the request to [https://docs.secretless.io/Latest/en/](https://docs.secretless.io/Latest/en/) and the message: "You do not have permission to view this directory or page."

**Comment by izgeri** [comment]
Thanks for reporting this @jcantosz! I'm looking into it now, and will hopefully have a fix in place shortly.

**Comment by izgeri** [comment]
@jcantosz the doc site has been updated and the link should now resolve correctly. I've been able to validate the problem and see it resolve myself, so I'll close this issue now - but please feel free to reopen if you're still seeing any problems on your end.

**Comment by jcantosz** [comment]
Thank you @izgeri ! That docs pages are working for me now
