### ISSUE TITLE
Secretless has a Red Hat certified container image

### ISSUE THREAD

**Issue by alexkalish** [cyberark/secretless-broker#1143]
# Secretless has a Red Hat certified container image

## Outcome

Customers can acquire an up-to-date and support Secretless Broker container image from Red Hat.

## Scope

* The Red Hat certified container image for the Authn-K8s has been updated. 
* The updated version includes the following changes: 
    * Update the RHEL base image used, as the current one is nearly EOL. 
* The process and instructions for releasing the authn-K8s client includes updating the certified Red Hat container image. 

## Risks

* There is a PM desired deadline for completion: April 2020 (i.e. Red Hat Summit). 
* Project timeline will be dictated by feedback loop w/ Red Hat 

## References
- Aha! Card: [Red Hat certification prior to Red Hat Summit (Apr 2020)](https://cyberark.aha.io/features/AAM-298)

## Team
- **Product Manager**: @boazmichaely 
- **Product Owner**: @alexkalish 
- **Engineering Manager**: @izgeri 
- **Feature Lead**: N/A 
- **Engineers**:
    - @BradleyBoutcher 
- **Technical Writer**: @yserota 

## SDLC Timeline

|Stage|Updates|Artifact|
|-|-|-|
|Project Start|![](https://img.shields.io/static/v1.svg?label=2020-02-10&message=Complete&color=blue)||
|Kickoff|N/A||
|Feature & Design Proposal|N/A||
|Functional Sign-off|N/A||
|Execution|![](https://img.shields.io/static/v1.svg?label=2020-02-10&message=Started&color=green)||
|Acceptance|![](https://img.shields.io/static/v1.svg?label=YYYY-MM-DD&message=Not%20Started&color=lightgrey)||

## Stories

_List the stories here._

**Comment by izgeri** [comment]
Note - the image is available in the RH registry, but hasn't been published yet. We need to work with RH to get it approved / published on their side, but the technical work on this is done for now so I am closing this issue.
