### ISSUE TITLE
Secretless RH certified publish pipeline logs into RH first

### ISSUE THREAD

**Issue by izgeri** [cyberark/secretless-broker#1145]
AC:
- [x] Update the `bin/publish` script to log in to the RH container registry before calling the `push` command.

You can follow the example pull request opened at cyberark/conjur-authn-k8s-client#83 that has the changes for `conjur-authn-k8s-client`.  For `secretless-broker`, the key to use in secrets.yml is at `redhat/projects/secretless-broker/api-key`.

**Comment by JakeQuilty** [comment]
Link to PR: https://github.com/cyberark/secretless-broker/pull/1149
