### ISSUE TITLE
MSSQL: Support for specifying client certificate with sslmode

### ISSUE THREAD

**Issue by doodlesbykumbi** [cyberark/secretless-broker#1166]
The parameters sslkey and sslcert specify the client's TLS key pair for use in the TLS connection between Secretless and the target service

## Acceptance Criteria
- [ ] Support exists for specifying a client's TLS key pair
- [ ] Unit/Integration tests for specifying client's TLS key pair

**Comment by izgeri** [comment]
@doodlesbykumbi can you look into whether MSSQL actually uses this and note what you find on this ticket?

**Comment by izgeri** [comment]
@doodlesbykumbi found the following:

https://social.msdn.microsoft.com/Forums/sqlserver/en-US/076e0764-576f-40a9-9bfc-b622e4ac8e22/sql-2014-certificate-authentication?forum=sqlsecurity

> SQL Server does not support mutual authentication via TLS. In other words, there is no certificate based client authentication available in SQL Server.

As such, we will not be adding this functionality to the MSSQL connector at this time.
