### ISSUE TITLE
MSSQL: Unit/Integration tests for each sslmode support

### ISSUE THREAD

**Issue by doodlesbykumbi** [cyberark/secretless-broker#1167]
This issue allows us to keep track of all the testing criteria in one place

## Acceptance Criteria (expected to be covered via other stories, but this story serves as a check)
- [ ] Unit/Integration tests exist for sslmode=disable
- [ ] Unit/Integration tests exist for sslmode=verify-ca
- [ ] Unit/Integration tests exist for sslmode=require
- [ ] Unit/Integration tests exist for the sslrootcert parameter
- [ ] Unit/Integration tests exist for the sslcert and sslkey parameters

## Additional tests that we may need
- [ ] Unit/integration tests exist for sslmode=verify-ca and sslmode=require with expired certs (sslrootcert, sslcert, and server cert)

**Comment by doodlesbykumbi** [comment]
@andytinkham 
re: 
> Unit/integration tests exist for sslmode=verify-ca and sslmode=require with expired certs (sslrootcert, sslcert, and server cert)

As things stand with MySQL and Postgres, sslmode=require without sslrootcet won't error with an expired server cert. sslmode=require with sslrootcert (and beyond) will.

**Comment by andytinkham** [comment]
Is that because of how the other connectors are coded or is that a side effect of something else? That seems like it's not desired behavior to me...

**Comment by doodlesbykumbi** [comment]
@andytinkham it turns out that it is desired behaviour. `require` doesn't do any verification of the server. It just ensures that there's an SSL connection. Verification is left to verify-ca.
