### ISSUE TITLE
MSSQL: Update troubleshooting wiki for sslmode

### ISSUE THREAD

**Issue by doodlesbykumbi** [cyberark/secretless-broker#1169]
Update troubleshooting wiki to reflect issues surrounding use of TLS support

## Acceptance Criteria
- [x] Troubleshooting wiki updated

Additional cases to consider:
- `sslmode` is `require` and the server can't do secure connections
- `sslmode` is `disable` and the server can only do secure connections

**Comment by izgeri** [comment]
@BradleyBoutcher once you have a wiki diff to share with the TWs to update the website documentation, please add the link for the diff to cyberark/secretless-docs#246

**Comment by BradleyBoutcher** [comment]
Initial commit posted

Diff: https://github.com/cyberark/secretless-broker/wiki/Troubleshooting-Guide/_compare/e189bb7e1a87553a0e4fd77e475422a570c9bddc...26b2fed497e74fecaa126a7858ff57bcf9ceb980
