### ISSUE TITLE
MSSQL: connector with SSL support has undergone XA

### ISSUE THREAD

**Issue by doodlesbykumbi** [cyberark/secretless-broker#1170]
MSSQL connector with SSL support has undergone XA

# Experience Assurance Plan

The infra team will deploy for you:
- A DAP master cluster
- A DAP follower in OC `3.11` dev
- An AWS RDS instance of a SQL Server 2017 Express Edition server, with SQL server authentication credentials stored in the DAP cluster (note: it is SQL Server Express Edition / 14.00.3281.6.v1 which according to https://support.microsoft.com/en-us/help/321185/how-to-determine-the-version-edition-and-update-level-of-sql-server-an is 2017)

You will be provided with:
- Credentials and cluster info for your Conjur user
- The policy branch with the database secrets which your user has `read` access on to see the IDs of the secrets you need
- The layer/group in DAP that has `read`/`execute` on the DB secrets
- The namespace/project where the DAP follower is deployed
- The URL of the DAP follower
- The Kubernetes authenticator name
- The DAP account
- The DAP x509 CA certifiicate chain for the DAP follower
- The cert for the MSSQL RDS instance

You will follow [the documentation](https://docs.secretless.io) (including the draft updates in cyberark/secretless-docs#246) to deploy the [pet store app](https://github.com/conjurdemos/pet-store-demo/) with Secretless so that the pet store connects to its backend MSSQL DB via Secretless (which is running as a separate container in the same pod).

**Comment by BradleyBoutcher** [comment]
I've completed XA, and here are my findings:

Modes tested:
- verify-ca, verify-full

Summary: 
- The mssql connector functioned as expected, and the only issues I encountered along the way were bumps in the road for the overall xa setup. This was my first time following the "Get Started" guide on the Secretless site, which was a small learning curve, but after going through it once, I was able to do it again quickly. 

MSSQL Connector Feedback:
- I focused my testing on the secretless config, which is the primary source of changes in this set of changes. There was nothing here that stood out as slow, a poor experience, etc. Running queries through a test application also succeeded without issue. And, when attempting to sniff out any confidential information through error messages, I was unable to do so.
- The docs on the staging site were clear enough, although it may be beneficial to link to Microsofts MsSQL documentation if a user needs more information on the sslmodes we're supporting.

Secretless Setup Feedback:
- When loading policies, there was no feedback which could indicate success or an error, which made troubleshooting configurations difficult.
- Users can load conjur policies with the `--replace` flag, which could cause issues, and the docs do not mention this feature. If a mistake is made during setup, my first instinct would be to reload the policies with the `--replace` flag.
