### ISSUE TITLE
An abstraction exists to facilitate MSSQL sslmode integration tests

### ISSUE THREAD

**Issue by doodlesbykumbi** [cyberark/secretless-broker#1187]
## Description

sslmode integration tests will need to assert on the propagation of parameters between secretless and the target service.  

At present we have a method called `propagateParams` in our integration tests. This method uses a mock server in this format `[client => secretless-the-binary => mock server]`. It allows us to send something from the client and make assertions on what is received on the mock server.

This issue requires that we extend propagateParams a little bit to allow us to test different combinations of params. secretless-the-binary is constrained and relies on the source of truth being Secretless config, which can't be reasonably modified at run time. The suggestion here is to switch the middle component from secretless-the-binary to just an invocation of the connector. This change gives us dynamic control of credentials passed to the connector while everything else sort of stays the same. This allows us to meet our goes of testing different combinations of sslmode parameters in-process.

AC:
- [ ] A user of this abstraction can input connection params  and expect in return a structure with all the data that the server sees throughout the lifecycle of the request. The user can then make assertions on this returned data.

**Comment by izgeri** [comment]
@doodlesbykumbi I don't think this is in the epic / milestone yet - can you please add it?
