### ISSUE TITLE
TLS verification behaviour is well-defined across sslmodes

### ISSUE THREAD

**Issue by doodlesbykumbi** [cyberark/secretless-broker#1190]
# Overview

As things stand with MySQL and Postgres, sslmode=require without sslrootcet won’t error with an expired server cert. sslmode=require with sslrootcert (and beyond) will. That it is not immediately clear if this is the intended behaviour warrants this spike. The purpose of this spike to clearly define the expected behaviour, in terms of TLS verification, across sslmodes.

# Definition of done
- [x] An artefact exists in the Secretless repo detailing the expected behavior across sslmodes.
- [x] The verification behaviour for each sslmode is defined, and covers the many aspects of cert verification (hostname, CA, expiry etc.)

**Comment by doodlesbykumbi** [comment]
This image really captures what disable, require and verify-ca mean
![image](https://user-images.githubusercontent.com/8653164/78921595-091b8f80-7a8d-11ea-8e5e-99863f005d79.png)

**Comment by izgeri** [comment]
@doodlesbykumbi I drafted a table to go into the documentation here: https://github.com/cyberark/secretless-docs/issues/246#issuecomment-614789638

I think it's best that this goes into the documentation.

on the other hand, is there work that can be done in the project to ensure we are testing (and implementing) the right things in our TLS connectors to be true to these definitions? that might be worth looking into

**Comment by doodlesbykumbi** [comment]
@izgeri The table you linked to is great! 

Agreed, it should be in the docs. 

I agree that since the expected behaviour is the same we should have some collection of tests that get run the same for each connector. I can imagine a mini-framework that 
1. Defines interfaces for running the client and target service
2. Testing a particular connector requires implementations of the client and target service interfaces for the connector
3. Using(2), the framework will set up Secretless and proxy a connection from the client through to the target service and carry out all the assertions.

**Comment by izgeri** [comment]
Filed #1225 for future work, closing this issue now
