### ISSUE TITLE
Tests exist for verifying that sslmode and certificates are propogated to the server

### ISSUE THREAD

**Issue by BradleyBoutcher** [cyberark/secretless-broker#1193]
Testing must be added to verify that each sslmode (disable, require, and verify-ca), as well as the root certificate, are propagated correctly to the server.

- [ ] Integration / unit tests exist for checking parameters have been propagated from secretless to the driver
- [ ] Integration / unit tests exist for verifying that the certificate has been processed as-needed by the driver and received / handled by the server

**Comment by izgeri** [comment]
@BradleyBoutcher @doodlesbykumbi do we have a mechanism for testing this now? we've left this out of test plans for other connectors due to its complexity (and coverage with unit tests)

wondering if this card can be dropped

**Comment by doodlesbykumbi** [comment]
I think...

The integration tests side of things on this card is covered by the contents of this other [card](https://github.com/cyberark/secretless-broker/issues/1167) (and the associated [PR](https://github.com/cyberark/secretless-broker/pull/1208)). 

I think what is missing and would be useful is a unit test for the [URL method](https://github.com/cyberark/secretless-broker/blob/master/internal/plugin/connectors/tcp/mssql/connection_details.go#L111) in connection details. We need to ensure it generates the DSN that the driver expects.

**Comment by doodlesbykumbi** [comment]
The integration tests side of things on this card is covered by the contents of this other [card](https://github.com/cyberark/secretless-broker/issues/1167) (and the associated [PR](https://github.com/cyberark/secretless-broker/pull/1208)). 

What is missing and would be useful is a unit test for the [URL method](https://github.com/cyberark/secretless-broker/blob/master/internal/plugin/connectors/tcp/mssql/connection_details.go#L111) in connection details. We need to ensure it generates the DSN that the driver expects.

**Comment by izgeri** [comment]
Filed #1224, closing this one now.
