### ISSUE TITLE
MSSQL connector TLS support has undergone security review

### ISSUE THREAD

**Issue by izgeri** [cyberark/secretless-broker#1195]
AC:
- [x] the security architect has reviewed the code changes

**Comment by izgeri** [comment]
@andytinkham we don't have the right `kind/` label for this kind of card - any ideas for what the right one would be? Maybe we need to add one?

**Comment by andytinkham** [comment]
> @andytinkham we don't have the right `kind/` label for this kind of card - any ideas for what the right one would be? Maybe we need to add one?

Sounds like the case, yes. I'll get one added.

**Comment by izgeri** [comment]
## Outcome of review
We talked through the STRIDE model and identified potential attacks in Information Disclosure and Denial of Service. 

### Information disclosure
- [ ] Check the log messages we write out to make sure we don't explicitly write out sensitive info
- [ ] Check the issues on the main go-mssqldb project to see if there are any information leakage issues known
- Long term - obfuscating known sensitive data including  error messages echoed from the server is worth exploring across all connectors

### Denial of Service
- What is the overhead of a go channel? Given Secretless creates a go channel for each connection, could Secretless or the target server be DoS'd by maliciously or accidentally creating a large number of connections at once? Also, if Secretless doesn't close out connections after set amount of inactivity, is it possible to consume all available open connections and DoS Secretless?

{TODO: add response here}

- What (if any) garbage collection occurs during the process of transferring data back to the client app? For example, if a query returned GBs of results, would Secretless choke and die, essentially DoSing itself?

{TODO: add response here}

- Long term - a solution might be to introduce a worker pool into Secretless across all connectors to effectively provide a throttle/load balancer effect but that's out of the scope of this effort.

### Summary
Other than addressing the 2 immediate actions and getting more info on the open questions, we didn't see anything else that needs handling right now.

**Comment by BradleyBoutcher** [comment]
> Check the issues on the main go-mssqldb project to see if there are any information leakage issues known

Searching through the existing go-mssqldb issues, I didn't see any that would be cause for concern on our part from a security or functionality standpoint.

**Comment by izgeri** [comment]
All questions have been responded to, so I'm closing this issue now.
