### ISSUE TITLE
There is an initial MSSQL 1 hour performance test

### ISSUE THREAD

**Issue by izgeri** [cyberark/secretless-broker#1209]
There is an initial 1 hour performance test for MSSQL using juxtaposer in OC 3.11.

As a first pass, you can run the test locally following the instructions [here](https://github.com/cyberark/secretless-broker/tree/master/bin/juxtaposer/#running-the-code-locally).

Starting early next week, we should also be able to run the tests using an XA environment with an actual DAP cluster, a follower in OC 3.11, and an MSSQL RDS instance. You can read through the configuration files in the juxtaposer directory  to learn more about what you'll need to edit there to get started.

**Comment by BradleyBoutcher** [comment]
One hour performance test completed locally
Results: 
```
--------------------------------------------------------------------------------------------------------------------------------------------------------------
Name                          |          Min|          Max|          Avg| 90% Lower %| 90% Upper %|             Total|   Rounds|   Errors|   Succ %| Thresh %|
--------------------------------------------------------------------------------------------------------------------------------------------------------------
mssql_direct                  |    701.061µs| 1.012428965s|   1.071753ms|      100.00|      100.00|1h19m37.546308347s|  4457690|        0|   100.00|     0.00|
mssql_secretless              |    771.655µs| 1.012224226s|   1.120228ms|      105.48|      105.67|1h19m38.065189889s|  4265260|        0|   100.00|     9.95|
--------------------------------------------------------------------------------------------------------------------------------------------------------------
```
