### ISSUE TITLE
There is a generic HTTP connector config for Elasticsearch

### ISSUE THREAD

**Issue by izgeri** [cyberark/secretless-broker#1212]
We have a [library](https://github.com/cyberark/secretless-broker/tree/master/examples/generic_connector_configs) of generic HTTP connector configuration files.

It would be nice to have an example for the [Elasticsearch REST API](https://www.elastic.co/guide/en/elasticsearch/reference/current/rest-apis.html), so that Secretless could be used with Elasticsearch.

**Comment by BradleyBoutcher** [comment]
Status update:

I have a work in progress configuration for the two means of authenticating through the API
```version: 2
services:
  token-service:
    connector: generic_http
    listenOn: tcp://0.0.0.0:9030
    credentials:
      token:
        from: keychain
        get: summon#elasticsearch/access_token
    config:
      headers:
        Authorization: Bearer {{ .token }}
      forceSSL: true
      authenticateURLsMatching:
        - ^http[s]*\:\/\/*
  api-key-service:
    connector: generic_http
    listenOn: tcp://0.0.0.0:9020
    credentials:
      id:
        from: keychain
        get: summon#elasticsearch/api_key_id
      api_key:
        from: keychain
        get: summon#elasticsearch/api_key
    config:
      headers:
        Authorization: ApiKey {{ .token }}{{ printf "%s:%s" .id .api_key | base64 }}
      forceSSL: true
      authenticateURLsMatching:
        - ^http[s]*\:\/\/*
```

I've been able to get the token route to work in my terminal, but haven't been able to get either to work when using secretless as a proxy, so I need to keep digging a bit
