### ISSUE TITLE
Secretless has run MSSQL performance tests with the latest master build (1.5.2-434b05c at this time)

### ISSUE THREAD

**Issue by izgeri** [cyberark/secretless-broker#1216]
AC:
- [x] [Juxtaposer](https://github.com/cyberark/secretless-broker/tree/master/bin/juxtaposer/) 1 hour, single thread, `recreateConnections=false` (aka persistent connection) performance tests have been run for MSSQL in a realistic environment (eg the XA env)
- [x] [Juxtaposer](https://github.com/cyberark/secretless-broker/tree/master/bin/juxtaposer/) 1 hour, single thread, `recreateConnections=true` performance tests have been run for MSSQL in a realistic environment (eg the XA env)
- [x] The tabular results of the performance tests have been attached to this issue
- [x] Aggregate results are also posted (using Aggregate.py)

**Comment by BradleyBoutcher** [comment]
OC Results:
--------------------------------------------------------------------------------------------------------------------------------------------------------------
Name                          |          Min|          Max|          Avg| 90% Lower %| 90% Upper %|             Total|   Rounds|   Errors|   Succ %| Thresh %|
--------------------------------------------------------------------------------------------------------------------------------------------------------------
mssql_direct                  |   1.393397ms| 683.636878ms|   2.156427ms|      100.00|      100.00|  59m53.837613835s|  1666570|        0|   100.00|     0.00|
mssql_secretless_tcp          |   1.429804ms| 684.769386ms|   2.195853ms|      116.73|      117.75|  59m53.924939692s|  1636687|        0|   100.00|     6.77|
--------------------------------------------------------------------------------------------------------------------------------------------------------------
