### ISSUE TITLE
There is a unit test for the URL method in the MSSQL connection details

### ISSUE THREAD

**Issue by izgeri** [cyberark/secretless-broker#1224]
- [ ] There is a unit test for the [URL method](https://github.com/cyberark/secretless-broker/blob/master/internal/plugin/connectors/tcp/mssql/connection_details.go#L111) in connection details. We need to ensure it generates the DSN that the driver expects.

**Comment by doodlesbykumbi** [comment]
For this I think a table-driven test should suffice. We'd need to call `NewConnectionDetails` for some permutations of the credentials map, and assert on what the URL method returns.
