### ISSUE TITLE
http_basic_auth supports "connector" key in lieu of "protocol" w/o error

### ISSUE THREAD

**Issue by jodyhuntatx** [cyberark/secretless-broker#1227]
## Summary
I heeded this warning, but http_basic_auth connector still requires “protocol” key, provokes errors if changed to “connector”.
```
2020/05/14 14:08:49 WARN: 'protocol' key found on service 'http_basic_auth'. 'protocol' is now deprecated and will be removed in a future release.
```

**Comment by sgnn7** [comment]
Hey @jodyhuntatx, 
I think this issue might be invalid:
```
$ ./secretless --version
secretless-broker v1.5.2-dev

$ cat  basic_auth.yml 
version: 2
services:
  http_basic_auth:
    connector: basic_auth
    listenOn: tcp://0.0.0.0:8080
    credentials:
      username: someuser
      password: testpassword
    config:
      authenticateURLsMatching:
        - ^http.

$  ./secretless -f basic_auth.yml 
2020/05/14 09:31:35 Secretless v1.5.2-dev starting up...
2020/05/14 09:31:35 Initializing health check on :5335...
2020/05/14 09:31:35 Initialization of health check done. You can access the endpoint at `/live` and `/ready`.
2020/05/14 09:31:35 [WARN]  Plugin directory '/usr/local/lib/secretless' not found. Ignoring external plugins...
2020/05/14 09:31:35 Trying to load configuration file: basic_auth.yml
2020/05/14 09:31:35 Registering reload signal listeners...
2020/05/14 09:31:35 [INFO]  Configuration found. Loading...
2020/05/14 09:31:35 [INFO]  Validating config against available plugins: ssh,ssh-agent,pg,mysql,mssql,aws,basic_auth,conjur,generic_http
2020/05/14 09:31:35 [INFO]  Starting HTTP listener on 0.0.0.0:8080...
2020/05/14 09:31:35 [INFO]  Starting HTTP subservice basic_auth...
2020/05/14 09:31:36 [INFO]  HTTP Proxy on tcp://0.0.0.0:8080: Starting service
^CReceived a stop signal
2020/05/14 09:32:14 [INFO]  Stopping all services...
2020/05/14 09:32:14 [INFO]  HTTP Proxy on tcp://0.0.0.0:8080: Stopping service
```

I don't see any errors in the output here ^. Is there a `version` key in your config?

**Comment by sgnn7** [comment]
Closing this as invalid for now as it turns out it was a config issue:
-`config_with_error.yml`
```
http_basic_auth:
    connector: http
    listenOn: tcp://0.0.0.0:8081
    credentials:
      ...
    config:
      authenticationStrategy: basic_auth
      authenticateURLsMatching:
        - .*
```
-`working_config.yml`
```
http_basic_auth:
    connector: basic_auth
    listenOn: tcp://0.0.0.0:8081
    credentials:
      ...
    config:
      authenticateURLsMatching:
        - .*
```
Feel free to reopen if needed @jodyhuntatx.

**Comment by izgeri** [comment]
reopening to ask one more question, before we consider this closed

@doodlesbykumbi do you know why this test is passing, given how it looks compared to Jody's original (bad) config?
https://github.com/cyberark/secretless-broker/blob/master/pkg/secretless/config/v2/config_test.go#L90

**Comment by doodlesbykumbi** [comment]
The deprecated `protocol` format requires/d specifying both `http` (protocol) AND `basic_auth` (authenticationStrategy).

The current `connector` format hides protocol details from the user. A service connector is identifiable by name, you need only specify `basic_auth`.

The test uses the old format. This will issue a deprecation warning but still works.

**Comment by izgeri** [comment]
Ah, thanks for clarifying! So looking more closely at the reported bad config, it used a mix of the old and new format. Re-closing the issue.
