### ISSUE TITLE
Secretless publishes images on tag-triggered builds

### ISSUE THREAD

**Issue by izgeri** [cyberark/secretless-broker#1233]
At current, Secretless master branch Jenkins pipelines run whenever there is a change to the master branch, and we determine whether to publish based on whether the most recent tag matches the current commit.

https://github.com/cyberark/secretless-broker/blob/8d7f757f7bcfb2cb26283e685da06e0cc8121d84/bin/publish#L36

We now have support in Jenkins for tag-triggered builds (docs link TBA), so we'd like to update the project to publish when it's a tag build rather than publishing based on a logical question that could fail if another commit is pushed to the master branch before the build completes.

**Comment by hughsaunders** [comment]
* [Docs on Jenkins triggers](https://github.com/conjurinc/docs/blob/master/reference/jenkins.md#jenkins-pipeline-github-triggers)
* [Example conditional stage for tag jobs only](https://github.com/cyberark/parse-a-changelog/blob/master/Jenkinsfile#L43)
