### ISSUE TITLE
Broken documentation links in README

### ISSUE THREAD

**Issue by mdodell** [cyberark/secretless-broker#1254]
## Summary
Two of the links in the main README.md file for Secretless are no longer valid.

## Steps to Reproduce
1. Go to the 'Currently supported services' section
2. Click either link with the 'documentation' text

## Expected Results
I should be redirected to the proper links in the Secretless documentation.

## Actual Results (including error logs, if applicable)
The first link goes to a [web page](https://docs.secretless.io/Latest/en/Content/References/Secretless%20Plugin%20Interface/Secretless_Plugin_Interface_Intro.htm) with the following text:
```
The resource you are looking for has been removed, had its name changed, or is temporarily unavailable.
```

The second link goes to a [web page](https://docs.secretless.io/Latest/en/Content/References/connectors/overview.htm) with the following text:
```
The resource you are looking for has been removed, had its name changed, or is temporarily unavailable.
```

**Comment by izgeri** [comment]
ah! thanks for filing.

it looks like the first one should be: https://docs.secretless.io/Latest/en/Content/References/Secretless%20Plugin%20Interface/scl_Secretless_Plugin_Interface_Intro.htm

and the second one should be: https://docs.secretless.io/Latest/en/Content/References/connectors/scl_connectors_overview.htm

@mdodell -  can you please put up a PR to fix?
