### ISSUE TITLE
There is an example generic HTTP connector config for Facebook

### ISSUE THREAD

**Issue by izgeri** [cyberark/secretless-broker#1265]
## Use case
I am a developer building an app that has to communicate with the Facebook API

## Additional details
TODO: before starting work, add details on how authentication works for this webservice, to determine whether implementing it as a generic HTTP connector is feasible.

## Acceptance criteria
- [ ] There is a generic HTTP connector config available in the [example generic HTTP connector configs](https://github.com/cyberark/secretless-broker/tree/master/examples/generic_connector_configs) for connecting to the Facebook API via Secretless

**Comment by JakeQuilty** [comment]
## Multiple API's
- [ ] 
- [ ] 
- [ ] 

Live Video API requires [App Review](https://developers.facebook.com/docs/app-review)

**Comment by JakeQuilty** [comment]
All of the API's authenticate in the same way, but the set up of the demo app sides are different. I focused on an example with Instagram, and mentioned that the rest of Facebook's tutorials could be used instead.
