### ISSUE TITLE
Kubernetes library dependencies are updated

### ISSUE THREAD

**Issue by izgeri** [cyberark/secretless-broker#1343]
## Description
At current, we depend on some k8s libraries:
```
>>> k8s.io/apiextensions-apiserver-0.0.0-20180808065829-408db4a50408
>>> k8s.io/apimachinery-0.0.0-20180621070125-103fd098999d
>>> k8s.io/client-go-0.0.0-20180806134042-1f13a808da65
```

I would like to update those to match recent k8s versions, but it's not clear if we want to support the last `N-3` Kubernetes versions whether we should include the v1.15 releases of these libraries or the v1.18 releases.

AC:
- [ ] Determine which version of the Kubernetes libraries we use we should upgrade to
- [ ] Update the project to use newer tags of the Kubernetes libraries we include

**Comment by imheresamir** [comment]
#1434 - Updated k8s libraries:
* k8s.io/api -> v0.22.3
* k8s.io/apiextensions-apiserver -> v0.22.3
* k8s.io/apimachinery -> v0.22.3
* k8s.io/client-go -> v0.22.3

Based on https://github.com/kubernetes/kubernetes/releases/tag/v1.22.3
