### ISSUE TITLE
Run experiment to determine throughput limits of Secretless

### ISSUE THREAD

**Issue by doodlesbykumbi** [cyberark/secretless-broker#1413]
For this experiment we need to increment the size of the data streaming through Secretless per unit time from 0 until we reach a point where the rate of streaming reaches a maximum.

NOTE that at this stage the traffic profile of interest is the light operating profile, defined as:

+ 2000 open connections
+ 10 active (transmitting) connection
+ 50 waiting (non-transmitting) connections

## Acceptance criteria

- [ ] For a light operating profile there is a reportable value for the maximum throughput

**Comment by alexkalish** [comment]
@doodlesbykumbi: Two questions:
1. When you saw "increment", do you mean increase the streaming data?
2. How do you know when "the rate of streaming reaches a maximum"?  Is it based on error rate?  Or will latency become too great?
Thanks!

**Comment by doodlesbykumbi** [comment]
@alexkalish 

1. Yes,  it's about incrementing the size of the request payload
2. I think there are several ways but the one I had in mind was to keep track of the throughput metric. Prior to the limit, as we increment the size of the request payload we expect the throughput to grow linearly. When we reach the limit then the throughput should should just stop growing.
