### ISSUE TITLE
Fix up minor k8s tutorial issues

### ISSUE THREAD

**Issue by sgnn7** [cyberark/secretless-broker#231]
A few things in the k8s demo could be improved:

- [ ] Many of the commands have no output shown so it will be difficult for people trying things out that they're on the right track.
- [ ] Inconsistency throughout in applying configuration files: piping to file content, streaming, showing what a file contains (expecting manual edit).
- [ ] After we expose app port, we should show what curl returns instead of just saying that they should try.
- [ ] First db login should show what the output should look like and how to exit `psql` CLI.
- [ ] Application deployment manifest - should be a single file edit - multiple steps and manual var substitution seems overly painful.
- [ ] Requires reduction in env var dependence. Much of the code isn't independently runnable and we already know what the values will be so it might be better to use hardcoded values in configs.
- [ ] The tutorial README should capitalize Kubernetes consistently
- [ ] The tutorial README references `quick-start.yml:35`, but this file doesn't exist anymore
- [ ] The tutorial README secretless.yml should be updated to match what's in `etc/secretless.yml`
- [ ] Ensure the tutorial in GitHub is consistent with the tutorial on the website

**Comment by izgeri** [comment]
Adding list as a comment in #353 and closing this issue
