### ISSUE TITLE
Instructions are available for using Secretless on a Jenkins executor for SSH and AWS proxy

### ISSUE THREAD

**Issue by kgilpin** [cyberark/secretless-broker#26]
On a Jenkins executor, a CI admin has simple instructions for running Secretless in such a way that:

* SSH key and Conjur API key are stored in files accessible only to root.
* SSH access uses Secretless.
* AWS CLI commands are proxied through Secretless.

**Comment by izgeri** [comment]
This issue was moved to cyberark/secretless-docs#87
