### ISSUE TITLE
Test suite docker-compose runs are namespaced to avoid collisions

### ISSUE THREAD

**Issue by doodlesbykumbi** [cyberark/secretless-broker#321]
Occasionally integration tests are failing when:
+ multiple jobs run on the same executor
+ a job runs and isn't cleaned up

One cause of failure is due to collisions in the names of the containers created by docker-compose.
Name-spacing docker-compose runs can clear this up.

**Comment by doodlesbykumbi** [comment]
@izgeri i haven't seen this come up in a while but i think it might still be relevant

**Comment by izgeri** [comment]
resolved in #905
