### ISSUE TITLE
Add OAuth2 HTTP handler

### ISSUE THREAD

**Issue by kgilpin** [cyberark/secretless-broker#328]
Adding support for OAuth2 handler will enable us to support all these backends : https://github.com/golang/oauth2

The handler should simply perform:

 ```
token := oauth2.Token{AccessToken: string(token)}
token.SetAuthHeader(r)
```

**Comment by izgeri** [comment]
Note: this could potentially be built using the [generic HTTP connector](https://github.com/cyberark/secretless-broker/tree/master/internal/plugin/connectors/http/generic) or possibly even written via config.
