### ISSUE TITLE
Take inventory of mobile fixes needed

### ISSUE THREAD

**Issue by typaulhus** [cyberark/secretless-broker#352]
Go through all of the pages on mobile device (multiple phone types & versions if possible) to see what needs addressing for small screens, and create GH Issues to fix.

Known: 

- [x] 1. Tabs are working on mobile, but are expanding slightly off the page
- [x] 2. top nav dropdowns are overlapping nav items, instead of pushing them down
- [x] 3. footer/jumbotron is not full length for iPhone 5
- [x] 4. blog card is longer than size of mobile screen
- [x] 5. docs banner's height needs to be increased (index and blog page)

**Comment by sigalsax** [comment]
added a few findings to description
