### ISSUE TITLE
Documentation is clear about connecting to Secretless locally without SSL (in particular for pg)

### ISSUE THREAD

**Issue by jodyhuntatx** [cyberark/secretless-broker#375]
brew install postgresql; brew link postgresql

$ psql -h localhost -p 5432 -U postgres -d quickstart
Password for user postgres:
psql: FATAL:  password authentication failed for user "postgres"

$ psql -h localhost -p 5454 -d quickstart
psql: FATAL:  SSL not supported

**Comment by izgeri** [comment]
This issue was moved to cyberark/secretless-docs#95
