### ISSUE TITLE
Broker is functionally capable

### ISSUE THREAD

**Issue by sgnn7** [cyberark/secretless-broker#382]
Parent of #31
Parent of #32
Parent of #50
Parent of #155
Parent of #260
Parent of #264
Parent of #265
Parent of #328

**Comment by izgeri** [comment]
Closing this epic since all stories are complete or also in other epics.

**Comment by izgeri** [comment]
Stories above are all still linked to this epic, so I'm editing the original description to break the link without losing the info about what was included.
