### ISSUE TITLE
Secretless FAQ answers the "dynamic secrets" comparison

### ISSUE THREAD

**Issue by brikelly** [cyberark/secretless-broker#397]
Our FAQ should speak to the dynamic secrets approach and say why the secretless solution is better.

We can say things like “other approaches to solving this problem propose creating secrets on-demand and expiring them aggressively. We believe that approach won’t be manageable at scale, nor does it truly get to the heart of the issue: applications shouldn’t have secrets in the first place.”

**Comment by izgeri** [comment]
This issue was moved to cyberark/secretless-docs#85
