### ISSUE TITLE
MySQL Handler returns useful error messages

### ISSUE THREAD

**Issue by izgeri** [cyberark/secretless-broker#41]
GIVEN I try to connect to MySQL with Secretless configured with an invalid username / password
THEN the connection should fail
AND the error code should be `Error: 1045 SQLSTATE: 28000 (ER_ACCESS_DENIED_ERROR)`

GIVEN I try to connect to MySQL with Secretless configured with an invalid MySQL host / port
THEN the connection should fail
AND the error code should be `Error: 2005 SQLSTATE: HY000 (CR_UNKNOWN_HOST)`

**Comment by sgnn7** [comment]
This was completed as part of https://github.com/cyberark/secretless-broker/issues/766. Closing.
