### ISSUE TITLE
Website main page architecture diagrams have better style

### ISSUE THREAD

**Issue by izgeri** [cyberark/secretless-broker#423]
Update the architecture diagrams on the main page so that:
- [x] the headings are centered appropriately over the images
- [x] the text "Secretless Broker Automates the Rest" is emphasized

depends on #415

**Comment by typaulhus** [comment]
I kept the heading left-aligned, but fixed the images so they'd stay in alignment with them. There was alot of extra padding and some width styling that causing issues.
