### ISSUE TITLE
Secretless has a MSSQL connector

### ISSUE THREAD

**Issue by izgeri** [cyberark/secretless-broker#452]
From @beaudryj:

# Secretless has a MSSQL connector

TBD

## Aha Cards
- [Link to Aha Card](https://cyberark.aha.io/features/AAM-93)

## Team
- **Product Manager**: Naama Schwartzblat 
- **Engineering Manager**: Geri Jennings (@izgeri)
- **Feature Lead**: TBD
- **Engineers**:
    - TBD

## SDLC Timeline
|Stage|Status|Date (or ETA)|Artifact|GH Issue|
|-|-|-|-|-|
|High Level Feature Doc| _started_ | _yyyy-mm-dd_ |[Feature Doc]() |[Link to Feature Doc GH issue]()|
|Functional Sign-off|Not Scheduled|_yyyy-mm-dd_|See above||
|Detailed Feature Doc|Not Done| - |[Feature Spec]()|[Link to Feature spec GH issue]()|
|Design doc| Done\ Not Done| [Design doc]|link to design doc|
|Solution Sign-off|Not Scheduled| - ||
|Execution|Not Started| - ||

**Comment by jodyhuntatx** [comment]
Epicor wants this.
