### ISSUE TITLE
CPU/memory consumption is measured

### ISSUE THREAD

**Issue by izgeri** [cyberark/secretless-broker#468]
Benchmarks exist to measure:

- [ ] CPU utilization (`cpu`)
- [ ] Memory utilization (`heap`)

These benchmarks can be collected using [pprof](https://golang.org/doc/diagnostics.html#profiling), and the process of completing the benchmarks is repeatable and documented to facilitate benchmarks being run on future releases.

**Comment by sigalsax** [comment]
Helpful to get proff up and running: https://flaviocopes.com/golang-profiling/

**Comment by izgeri** [comment]
The profiling is affected by the bug filed at #573, but which is resolved in the `pg/to-verify-ca` branch. This PR is on hold until the `pg/to-verify-ca` branch is merged.
