### ISSUE TITLE
Sidebar nav collapses at mobile viewports

### ISSUE THREAD

**Issue by typaulhus** [cyberark/secretless-broker#478]
On mobile screens, the sidebar navigation is being displayed at the top of the page (right underneath the top nav) and is pushing content off-screen. 

This should be either included into main navigation, or as a separate collapsable nav. (we need to define this before starting)

**Comment by sigalsax** [comment]
can you attach a picture of what you see and on what pages you see this? thanks!

**Comment by typaulhus** [comment]
@sigalsax I think we can delete this... this was about the subnav items in the documentation pages, but they're moving to Flare, so I think we can close this.

**Comment by sigalsax** [comment]
sure thing!
