### ISSUE TITLE
Remove dependency on Bash v4

### ISSUE THREAD

**Issue by izgeri** [cyberark/secretless-broker#494]
Test script should not require Bash v4, since it is not installed by default on Macs.

**Comment by jonahx** [comment]
I am going to split this up, since I'm not sure what's involved in fixing the mercurial dep atm.

**Comment by izgeri** [comment]
@jonahx did this end up getting fixed? Wondering if we can close this story.

**Comment by jonahx** [comment]
@izgeri yeah see above, it was merge here:

https://github.com/cyberark/secretless-broker/pull/497

**Comment by izgeri** [comment]
Closed, since this was resolved in #497
