### ISSUE TITLE
Logs have been reviewed to ensure they do not leak secret data

### ISSUE THREAD

**Issue by izgeri** [cyberark/secretless-broker#495]
The purpose of this issue is to devise a plan to ensure Secretless will not leak secret data to logs, neither in the code's current state or going forward. There are a few potential ways of ensuring this will be the case; some of the options are listed below, and this merits further exploration to discover others and decide on the best option for the nearterm.

We generally can't control logs in upstream libraries; this effort is focused primarily on ensuring the broker's own logs do not add risky data to the log stream.

## Review of Code Option
Review the current codebase to ensure any log output does not include secrets. Going forward, carefully review all PRs to check any logging that is added at any time in the future, and ensure it will also not leak secret data.

## Standard Logging Library Option
Write a standard logging library that Secretless can import and use for all logging. Flag PRs that use anything outside of the standard logging library.

## Automated Tests Option
There exists an automated test for all handlers and providers to ensure that:
- when Secretless is started configured to use the handler/provider pair 
- when Secretless opens a connection
- no secrets are leaked to Secretless logs

The check of whether secrets are leaked to logs can be done automatically (for ex with grep). The test functionality to auto-generate secretless YAML configs may be utilized.

Tests must be run both with and without debug mode on.

AC:
- [ ] There is a test for each handler and each provider that verifies that no secret data is dumped to logs when starting up Secretless or when opening a connection
- [ ] The tests are repeated with debug mode on and debug mode off

**Comment by sgnn7** [comment]
This could be an automated check of docker logs during integration tests probably rather than a manual one.

**Comment by izgeri** [comment]
@doodlesbykumbi @sgnn7 any ideas about a more specific description for this one? it's part of a handful of security stories that would be good to wrap up soon, but looking at it now I'm not sure I'd know where to get started if I pulled this story

**Comment by sgnn7** [comment]
@izgeri this one is tricky but I think we would need to rotate through providers and listeners in some way and connect to secretless while watching the stdout/stderr of secretless never outputs a secret value that we expect. If we standardize secrets we use in integration tests, our integration runner can just watch secretless output and fail the run if it encounters that secret value in the stdout/stderr.

**Comment by doodlesbykumbi** [comment]
@izgeri I'd go with redefining the story so that the deliverable is "automated review to ensure logs do not leak secrets"

I echo @sgnn7's comment to `grep`  (or otherwise) docker logs during integration tests. FWIW the testing framework for MySQL and Postgres allows dynamically generating `secretless.yml` so we can have all the providers and listeners running with relative ease.

**Comment by izgeri** [comment]
@sgnn7 @doodlesbykumbi please take a look at the updated description and lmk what you think; if it looks good, I'll move this to defined.

**Comment by izgeri** [comment]
@doodlesbykumbi tried to clarify, though I left my "test for all handlers" language in there bc I think it's generic enough and the person implementing this may do so however they see fit, which may mean writing one test that encompasses all handlers or by adding a set of relevant tests to each handler individually. I don't want to be too prescriptive, as I think it's fine that the implementer can decide this level of detail. If it looks good to you, please move it to defined. Thanks!

**Comment by izgeri** [comment]
@jonahx can you please add your summary of what you did here and close the issue ASAP?

**Comment by jonahx** [comment]
I manually reviewed the code instances of possible leaks.  Scanned through results for `Printf`, `Println`, etc.  Did searches for the word debug and scanned relevant results.  Manually reviewed Handler code.  I'd consider what I did a decent sanity check for Beta but by no means airtight.
