### ISSUE TITLE
Secretless is updated to use cyberark/goreleaser

### ISSUE THREAD

**Issue by izgeri** [cyberark/secretless-broker#501]
The release process is updated to use [CyberArk's goreleaser Docker image](https://github.com/cyberark/goreleaser-docker) rather than its own implementation.

**Comment by izgeri** [comment]
@sgnn7 since the updates to the official goreleaser image, is this still worth doing? Wondering if I can close this issue

**Comment by sgnn7** [comment]
@izgeri The new official version is more than sufficient. Closing.
