### ISSUE TITLE
secretless.io navigation is updated to reflect docs website

### ISSUE THREAD

**Issue by typaulhus** [cyberark/secretless-broker#554]
Update the navigation (top nav and footer links) on secretless.io to reflect move to docs.secretless.io. See attached wireframe for reference

![secretless_navigations](https://user-images.githubusercontent.com/123787/49475294-d69cbb00-f7e4-11e8-87b4-9c9a14669cc8.png)

**Comment by sigalsax** [comment]
Before I can begin, I am in need of more detail as to what needs to be done.

**Comment by sigalsax** [comment]
Task breakdown:
- Point the top nav to the new flare site 
- remove the documentation pages.
