### ISSUE TITLE
Secretless flare documentation site has updated design

### ISSUE THREAD

**Issue by izgeri** [cyberark/secretless-broker#581]
The Secretless flare docs site has updated design based on the comps created in #553.

Depends on #553

**Comment by izgeri** [comment]
@yserota I created this issue to track this work, and assigned it to you since I don't think your developer is on here. Can you please keep this up to date in waffle?

**Comment by yserota** [comment]
@izgeri, who can add Shlomo.Sagir@cyberark.com to this repo?

**Comment by yserota** [comment]
Drop 3.0.16 issues

- [ ] The highlights are too far apart and to small for this design
- [ ] Not enough space on the left.  
- [ ] *How can we help you* message is clipping the search bar
- [ ] The in page navigation only includes the H1

**Comment by izgeri** [comment]
@yserota are these issues things you need @typaulhus to help with? does the design need to be revised, or is there more info that you need?

this is a public repo, so @Shlomo-Tech-Tav should be able to see this gh issue, our [waffle board](https://github.com/cyberark/secretless-broker), and add comments / etc. if any changes to this repo are needed, he should be able to fork it and submit a PR.

please let me know if you run into issues @Shlomo-Tech-Tav!

**Comment by izgeri** [comment]
@typaulhus is there anything else left on this, or is it all being tracked in cyberark/secretless-docs? Can you link to that issue here and close this one if it's set?

**Comment by izgeri** [comment]
Moved to cyberark/secretless-docs#16
