### ISSUE TITLE
Demos and tutorials do not use debug mode

### ISSUE THREAD

**Issue by izgeri** [cyberark/secretless-broker#584]
All demos and tutorials with Secretless configurations should be updated to not use debug mode.

AC:
- [ ] All example secretless.yml files provided should not include `debug: true`
- [ ] Documentation that mentions the debug option should include the caveat `For development use only`
- [ ] The CONTRIBUTING file should reference the existence of the debug option and clarify what it applies to (eg handlers, but not providers at this time, etc)

**Comment by sgnn7** [comment]
I'd add an addendum: I think even with debug mode, we might not want to show any secrets either (e.g. I did something like that [here](https://github.com/cyberark/secretless-broker/blob/master/internal/app/secretless/listeners/http/listener.go#L147) we only print out the variable keys even with debug on).
