### ISSUE TITLE
Draft a Refactoring Plan

### ISSUE THREAD

**Issue by jonahx** [cyberark/secretless-broker#587]
Some potential areas of improvement that will be considered in the refactoring plan:
- Revise listener implementation to reduce repeated functionality
- Clean up the plugin interface to facilitate plugin contribution
   - To remove unneeded functionality 
   - To ensure all needed functionality is there 
   - To revise language/naming used for clarity

**Comment by jonahx** [comment]
Write up a plan for review of all the refactoring tasks, and their priorities.

Will pair with Kumbi on this.

**Comment by izgeri** [comment]
@jonahx I added a description from my earlier notes. Can you add a few more bullets for things that you plan to consider for this? I know we've learned more since we created the list that I added (for ex about refactoring to facilitate unit testing, etc)
