### ISSUE TITLE
Breakdown Testing Cleanup Tasks for PG / MySQL Handlers

### ISSUE THREAD

**Issue by jonahx** [cyberark/secretless-broker#589]
At current, the test infrastructure is in flux as we move to having more common functionality for our integration tests and consider best practices to enable better unit testing. As part of this spike, we will review the current state of the codebase for the pg/mysql handlers specifically and make specific recommendations for work to be done to improve the current state of the pg/mysql handler tests and test infrastructure. The end goal is to make it easier to add new tests and to improve the overall test coverage of the project; lessons learned from this process may be applied to other handlers / broker components in future work.

In particular, we have the following goals as part of this spike:
- Identify key improvements to make to the tests for the pg / mysql handlers that will enable us to simplify the tests to use best practices.  Improve both consistency and reliability of the tests. Lessons here can be transferred to other parts of code base in future efforts.  See [this talk](https://speakerdeck.com/mitchellh/advanced-testing-with-go) for ideas. 
- Identify missing tests for the pg / mysql handlers

**Comment by jonahx** [comment]
For the pg/mysql handler test code

**Comment by izgeri** [comment]
@jonahx is it correct that this spike is done?

**Comment by jonahx** [comment]
yes that gist was the result of this spike.
