### ISSUE TITLE
Add troubleshooting guide

### ISSUE THREAD

**Issue by doodlesbykumbi** [cyberark/secretless-broker#599]
A troubleshooting section in the documentation - perhaps checklists

Particularly for connecting to a DB with Secretless. This addresses the issue that sometimes when the connection is not working as expected potentially due to misconfiguration there's an inclination to assume something wrong with Secretless, which in many cases won't be the case (hopefully).

**Comment by izgeri** [comment]
This issue was moved to cyberark/secretless-docs#83
