### ISSUE TITLE
The favicon for secretless.io is not blurry

### ISSUE THREAD

**Issue by typaulhus** [cyberark/secretless-broker#606]
The favicon on secretless.io is pixelated and blurry with a white background showing. Update to use a sharper version with transparent background (attached.)
[secretless_favicon.zip](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/594aa0fa1fc1d1001ab8563b/125516c66e82c728ace21e0d46fb9199318797a58afaac7ca25ce69d2a4929316546b3397f8fe62bab0021435a0e18a844510a44a8fc8f2ca4b13c708b0808ef836a0970d42103eee9dc4be05ce36ade0d97bcae8b45cae93821e0838b4e3f1603198ffb4f78.zip)
![Screen Shot 2019-01-18 at 2.53.31 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/594aa0fa1fc1d1001ab8563b/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5700b77226455fb6b7191a37af117284f5c5e5ecc3c4a4356bcbbd671f3e57862804e0ebc87695a7d933d45a9be851db801ba21df4c87e4bbdc48d2f42f67b6d5db1063474f4dcbed5727a19e41c95df24ce94954a6163467e37f2431.png)

**Comment by izgeri** [comment]
closing as `wontfix`
