### ISSUE TITLE
Secretless has a 404 page

### ISSUE THREAD

**Issue by izgeri** [cyberark/secretless-broker#621]
A page is added to the Secretless website that the docs can redirect to when a resource isn't found.

AC:
- [x] The 404 page exists on secretless.io
- [x] On trying to navigate to a non-existent page on secretless.io, a user is redirected to the 404 page
- [ ] The 404 page assets have been sent to the docs team to add them to docs.secretless.io.

**Comment by izgeri** [comment]
Once this is complete, we can update the docs site to redirect to this page instead of displaying
https://user-images.githubusercontent.com/26872683/51996267-67f57a00-2482-11e9-9e42-b7a3a10d6d23.png
which is not very helpful.

**Comment by typaulhus** [comment]
![secretless_404.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/594aa0fa1fc1d1001ab8563b/125516c66e82c728ace21e0d46fb9199318797a58afaac7cf00da4d665043761260ea62864c7b96aea437d555a561bac155d5943fefe892ba7e23f72d85b5de9c3714d36976345f3e5db55ea43a82a994e82bcbd8f48c9e83820e28f8a473a1f1755.jpg)

**Comment by izgeri** [comment]
@typ this works for me. According to @garymoon he needs a url to direct 404s on the docs site to - so I was thinking if we add it to secretless.io, docs.secretless.io can redirect to it as well.

**Comment by typaulhus** [comment]
@sigalsax Here is an SVG for the graphic, and the repeating background. Let me know if you need anything!

[404 assets.zip](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/594aa0fa1fc1d1001ab8563b/125516c66e82c728ace21e0d46bcc4ce638390ba8afdac01e81fe086264c22703d46f9692584e57cea1b7e510b5a48ab435f5f44fdad8a29f4b16a74984019af80330b2b9b645bf9fa9015ad00b32a8a4a81bfbf8a4ac6ef3d20e48c9d02.zip)
