### ISSUE TITLE
MySQL Handler has comprehensive developer README

### ISSUE THREAD

**Issue by jonahx** [cyberark/secretless-broker#626]
This should give a high-level overview suitable for getting a new developer wholly unfamiliar with the MySQL protocol quickly up to speed.  It should give all context needed to understand the handler and the protocol, and point out any potentially confusing issues or details.

It should include the ascii art diagram from here:

https://gist.github.com/jonahx/3a400bf335d546d7750804d5057d6262

**Comment by izgeri** [comment]
I'm not sure exactly how our developer docs are evolving, but I think they've evolved past the point where we'll resolve this issue. Closing it now...
