### ISSUE TITLE
404 page image has been updated

### ISSUE THREAD

**Issue by sigalsax** [cyberark/secretless-broker#633]
When users reach a page not found, we wanted to enhance their experience by making them smile. To do so, we need to add a more detailed drawing to the 404 page

Personally, I was envisioning something like the following:
But instead of the little bean heads, make their heads in the shape of a cyberark vault. Open to more suggestions :)
![image 1](https://user-images.githubusercontent.com/19418506/52395909-75c98180-2ab8-11e9-9d8d-357c8f4e8e0f.png)

**Comment by izgeri** [comment]
I'd prefer to stick to the secretless theme / logos for this site - do you have any ideas or suggestions that would fit better with that theme?

**Comment by sigalsax** [comment]
Well we can definitely make the figures keys or little vaults. But that would be up to Ty what he envisions

**Comment by izgeri** [comment]
Ok. Let's just try to find a way to keep it on theme. In this pic, it looks like the little bugs are stealing the 404 - as if the page is not found bc they took it. What would be a way to make this into something that is linked to what Secretless does?

**Comment by izgeri** [comment]
this was completed quite a while ago - closing this issue now
