### ISSUE TITLE
Postgres uses same configuration fields as mysql

### ISSUE THREAD

**Issue by doodlesbykumbi** [cyberark/secretless-broker#661]
The mysql protocol takes a `host` and `port`
The postgres protocol takes an `address`

AC:
- [ ] MySQL protocol config uses `host` and `port`
- [ ] PG protocol config uses `host` and `port`
- [ ] All documentation is updated to match the new change
  - [x] Moved to https://github.com/cyberark/secretless-docs/issues/181

Old issue content for reference:
```
This makes it difficult to switch from one database to another. A user also has to take care to store their secret in a certain format .e.g. as an address for postgres and split up for mysql.

It might be worth considering splitting secret lookup and secret usage. Secret usage might benefit from the ability to specify templates .e.g `mysql://${db/host}:${db/port}`
```

**Comment by izgeri** [comment]
The lookup/usage split seems like a whole other issue

But I totally agree, address v host/port is not ideal. We should pick one and use it consistently, or support both.

**Comment by izgeri** [comment]
In addition, both handlers _require_ a port, even though many databases have a default port. For example, we could assume if no port is provided that pg is using 5432 and mysql is using 3306. But instead, we require a port in both cases.

I would like to see us update to a standard format and make host optional (with default values used, when applicable).

**Comment by sgnn7** [comment]
I think I'd +1 all of the comments here so we have a majority consensus of prefering host + port vs address so I think this is defined enough to be worked on (in this case meaning that PG will be moved to use host/port instead of address field.
