### ISSUE TITLE
K8s CRD Test Works Correctly

### ISSUE THREAD

**Issue by jonahx** [cyberark/secretless-broker#673]
Fix bug in K8s CRD Test

Currently the K8s CRD Test is:

1. Unclear in its output
2. Has a bug in that it doesn't actually test what we need
3. Could probably be automated using GKE cluster

## Unclear in its output

Current output:

```
~/cyberark/secretless-broker/test/manual/k8s_crds (beta-release) $ ./deploy 
Stopping deployment...
Deploying...
Error from server (NotFound): customresourcedefinitions.apiextensions.k8s.io "configurations.secretless.io" not found
Error from server (NotFound): services "secretless-broker" not found
Error from server (NotFound): services "secretless-broker-external" not found
Error from server (NotFound): clusterroles.rbac.authorization.k8s.io "secretless-crd" not found
Error from server (NotFound): rolebindings.rbac.authorization.k8s.io "secretless-crd" not found
Error from server (NotFound): clusterrolebindings.rbac.authorization.k8s.io "secretless-crd" not found
Error from server (NotFound): serviceaccounts "secretless-crd" not found
Error from server (NotFound): deployments.extensions "secretless-k8s-test" not found
Deploying...
clusterrole "secretless-crd" created
serviceaccount "secretless-crd" created
clusterrolebinding "secretless-crd" created
deployment "secretless-k8s-test" created
service "secretless-broker" created
service "secretless-broker-external" created
Deployment done!
```

We should:

- Redirect stderr to /dev/null because it has expected error output which
  misleadingly implies something went wrong with the test.
- Add a clear "Your test was successful" at the end of the test

## Has a bug in that it doesn't actually test what we need

We need to actually test that the pods have come up. That is, we need to do:

$ eval $(mk docker-env)

so that docker is pointed to kubernetes. And then:

$ kg get pods

and check that the status is running.

## Could probably be automated using GKE cluster

Kumbi has an idea that would allow us to automate this entire manual test.

TBD

**Comment by doodlesbykumbi** [comment]
Here's the idea that would allow us to automate this entire manual test.

- [ ] parametrise namespace in tests
- [ ] parametrise CRD name to allow for parallel test runs
- [ ] push secretless image to container registry
- [ ] authenticate gcloud container with kubectl using summon
- [ ] run test script inside gcloud container

**Comment by izgeri** [comment]
@jonahx can this issue be closed?

**Comment by izgeri** [comment]
There are revised k8s CRD tests now in `k8s-ci/` in the project, so this issue can be closed.
