### ISSUE TITLE
supported authentication mechanisms per handler are documented 

### ISSUE THREAD

**Issue by doodlesbykumbi** [cyberark/secretless-broker#687]
Ultimately handlers are made up of 2 things:
1. General Protocol Awareness
2. Implementations of Authentication Mechanisms e.g. Mongo has SCRAM (Default), x.509 Certificate Authentication etc.

The bare minimum for a handler to be called 'supported' is 1. and at least one of 2.

Documenting the status of each handler is important:
- [ ] to manage our development efforts
- [ ] to be transparent to users of Secretless about what's currently available for consumption e.g. https://github.com/golang/go/wiki/SQLDrivers

**Comment by izgeri** [comment]
Moved to cyberark/secretless-docs#164
