### ISSUE TITLE
website broken link to credential providers list in the faq

### ISSUE THREAD

**Issue by ryancnelson** [cyberark/secretless-broker#688]
the FAQ page at https://docs.secretless.io/Latest/en/Content/FAQ/faq.htm
contains a link to a "Credential Providers" page, linking to:
https://docs.secretless.io/docs/reference/providers/overview.html
... that page gives the 404 error code and message.

**Comment by ryancnelson** [comment]
looks like the proper link should go to: 
https://docs.secretless.io/Latest/en/Content/References/providers/overview.htm

**Comment by jonahx** [comment]
Thanks for flagging this @ryancnelson!

@yserota The corrected link Ryan gave is the right one.  Please include this change on the next republish.  Thanks!

**Comment by jonahx** [comment]
@ryancnelson This is now fixed.  Thanks again.
