### ISSUE TITLE
The configuration data structures match the revised Secretless syntax

### ISSUE THREAD

**Issue by jonahx** [cyberark/secretless-broker#710]
AC:
- [ ] There are new data structures that correspond to the revised configuration syntax
- [ ] (TBD how) the updated data structures can be used to instantiate the correct components on the backend

**Comment by jonahx** [comment]
Details TBD

**Comment by izgeri** [comment]
@doodlesbykumbi I put this story in `Defining` - once you have a better idea of what it will require, please update the description and add an AC checklist.

**Comment by izgeri** [comment]
@jonahx can this story be closed?

**Comment by sgnn7** [comment]
I think this is done so I'll close. @jonahx feel free to reopen if needed.
