### ISSUE TITLE
Secretless configuration syntax is versioned

### ISSUE THREAD

**Issue by jonahx** [cyberark/secretless-broker#714]
In an effort to ensure that old secretless.yml configurations are still supported to ease transition to new format, we will add versioning to the configuration.

Version 1 will not be referenced in any official documentation but will remain supported. We will not document it because we want to strongly encourage moving to the new format, while not pulling the rug out from under existing users.

The new version defined in #708 will be version 2. By default if there is no version in the specification, we will assume the user has given us something that is version 1. If we are unable to parse the configuration as version 1, Secretless will fail with invalid configuration and ask if the user wanted to specify a version.

AC:
- [ ] Secretless configuration syntax is versioned
- [ ] Secretless configuration works as described above when no version is specified

**Comment by izgeri** [comment]
Is this story about writing some code to map the old format to the new? If not, then shouldn't this just be part of the acceptance criteria for the changes that are made? Are we going to maintain or add some tests to ensure we continue to support the old format?
