### ISSUE TITLE
Secretless has a test app to exercise the database handlers

### ISSUE THREAD

**Issue by izgeri** [cyberark/secretless-broker#725]
# Description
In this task, we will write an application that can be deployed as a container to OpenShift. We will use this application to validate:
- The stability of Secretless Broker in handling database connections
- The request throughput is within 20% of direct-to-DB speed

## Requirements for the application
- Can be deployed as a container (eg there is a Docker image)
- Is reusable, so the code should be added to an existing GitHub repository or a new repository should be created
- Can connect to PostgreSQL and/or MySQL
- Can retrieve its database connection info from its environment, which may include address, username, and password or just address (if connecting via Secretless)
- The app should support the following connection modes:
  1. Open a connection, keep the connection open indefinitely, send regular / frequent queries, and print clear errors to stderr if the connection fails
  1. Open multiple connections at once, add query load, and print clear errors to stderr if the connection fails
  1. Continuously open connections and send queries, and print clear errors to stderr if the connection fails
  1. Open a connection, send a number of queries, measure the time for each query request, and print clear query time info to stdout

## Application tracking requirements
The application should track:
- The direct-to-DB query time data vs the query data via Secretless
- Any errors that the application logs, and the connection mode / database backend that caused that error (and any other relevant data)

# Open Questions

- Can the app be monitored so that we are alerted about errors reported in its logs?
- Are there other connection modes that the app should support? Are the current modes well enough defined?
- Are there other indicators that we need to capture and compare? Return codes? Connection properties?
- Are there ways to make this pluggable, so we can drop in new connection modules for things like HTTP, SSH, etc.?

# AC:
- [ ] An application exists that fulfills the functionality described above
- [ ] A manifest exists to deploy this application to OpenShift (without Secretless), retrieving the credentials for the database connection from Kubernetes Secrets

**Comment by andytinkham** [comment]
If possible, in addition to the above, it would be nice to have 

- the application track times to open & close a DB connection, with & without Secretless
- compare the results of the query made through Secretless to that made without Secretless to ensure the same results come back. I'm not sure what the best result set for this would be - do we need to have a large query result? A query result with a variety of data types? Not sure exactly how this could fail if there's a bug (truncation feels more likely to me than mutation of the results, though).
- if there are other values like return codes from methods or connection properties that we think might look different between the with Secretless and without Secretless modes, compare those
- the ability to rotate the password during app execution to ensure Secretless keeps functioning. This might complicate the connect without Secretless portion.

**Additional Open Questions**
- If the app does find that any db connection is dropping (either the long-term one or the short-term looping ones), what do we need to know to figure out why and fix the underlying issue?
- Are there ways that Secretless could fail but continue to make new connections? If so, can we extend the app to detect these failure scenarios as well?
- If we add query results comparison, is there anything we need to add to better diagnose why a results compare failed if it does happen?

**Comment by izgeri** [comment]
Note on what the app contains relative to the epic AC:


- [ ] Secretless is stable
  - [ ] It does not randomly drop connections while running
  - [ ] It can run without failure for an extended period of time (~4 days)
  - [ ] It can consistently open connections while running
  - [ ] When it fails, the pod is destroyed and rescheduled
- [ ] Secretless is easy to set up, and setup takes less than 10 minutes
  - This assumes DAP is already deployed and configured to use the Kubernetes authenticator - that is, "Secretless Setup" is the set of steps that the developer takes in the description below
- [ ] Secretless has minimal impact on connection speeds
  - [ ] Request throughput is within 20% of direct-to-DB speed
- [ ] Secretless performs under load in a realistic environment
- [ ] Secretless handles connections transparently, so that requests from the client are appropriately transmitted to the server and messages from the server are propagated back to the client
