### ISSUE TITLE
Secretless production ready release has been through XA

### ISSUE THREAD

**Issue by izgeri** [cyberark/secretless-broker#733]
The [demo app](https://github.com/conjurdemos/pet-store-demo) is used to validate the experience of adding Secretless with DAP to an existing application using the website and documentation.

This will involve creating:
  - The demo app configured to connect via Secretless
  - Secretless configured to connect to DAP using the Kubernetes authenticator

The time to deploy the test app with Secretless will be measured. 

The output of this card will be:
- [x] Notes on any issues that arise as a result of these tests
- [x] Info on how long it took to add Secretless to the test app deployment

**Comment by izgeri** [comment]
@apotterri I created a `alan-secretless-xa` namespace for you in our OC 3.9 cluster (creds in ConjurOps)

Feel free to use the namespace however you'd like to prep for XA. I'll be adding more info to this ticket with what you will need to know about the DAP deployment and the databases in the next day or so, but generally the idea is that the following will be set up for you:
- DAP master cluster in AWS
- DAP follower in its own namespace in OC
- MySQL and PostgreSQL DBs deployed to AWS with creds stored in DAP

You'll use that info to set up your app to connect to the DB via Secretless. We've been using the [pet store app](https://github.com/conjurdemos/pet-store-demo) for test cases like this (it's used in https://github.com/conjurdemos/kubernetes-conjur-demo, for example, both with and without Secretless) - I suggested it in the card description as the app to use to run through XA.

**Comment by izgeri** [comment]
For this XA:

- Deploy the [demo app](https://github.com/conjurdemos/pet-store-demo) using Secretless
  - Follow the [staging documentation](https://docs-staging.secretless.io) (and any other publicly available documentation or GitHub content that you find relevant)
  - Use the `alan-secretless-xa` namespace in the OC 3.9 cluster. The DAP master cluster, DAP follower, and databases are already deployed. The system information you'll need is:
    - `DB_POLICY_BRANCH`: `secretless-xa-db` - the pg address is in `postgresql/hostname` in this branch and the mysql host/port are in `mysql/hostname` and `mysql/port`
    - `DAP_SECRET_LAYER`: there is actually a `secretless-xa-db/readers` group that you can add your hosts to
    - `DAP_FOLLOWER_NAMESPACE`: `xa-secretless`
    - `DAP_FOLLOWER_URL`: `https://conjur-follower.xa-secretless.svc.cluster.local/api`
    - `AUTHENTICATOR_NAME`: `openshift/secretless-xa`
    - `DAP_ACCOUNT`: `xa`
    - `conjur.pem`: I loaded this into the `dap-ssl-cert` configmap in your namespace with the key `ssl-certificate`

- Keep track of the approximate time it takes you to deploy the app with Secretless.

**Comment by apotterri** [comment]
I had an issue figuring out how to get started with XA for this. It wasn't at all clear to me that I needed to go to the "Installation" section of the doc -- I kept wanting to find something in the "Getting Started" section. I wonder if there's some way to guide a new user to "Installation"?

Once I found the page in the "Installation" section titled "CyberArk Dynamic Access Provider", things went more smoothly. From an experience perspective it was mostly good. I did find it hard to deal with substituting the variables into the various YAML files. It took careful reading of a few of them to realize all the places that needed to be updated.

In addition, I found some other minor issues, which are documented in the images in the attached zip file.

Overall, it took about 30 minutes to get all the updates made and the demo app deployed.

**Comment by izgeri** [comment]
I took the ZIP files that @apotterri provided and created this list:

Things that are fixed in https://github.com/cyberark/secretless-docs/pull/163:
- The link to `PostgreSQL Service Authenticator` [here](https://docs-staging.secretless.io/Latest/en/Content/Get%20Started/using-dap.htm#WritetheSecretlessconfigurationfile) is using `MadCap:xref` and dropping the valid display text, so it reads `refers to the PostgreSQL using` instead of `refers to the PostgreSQL service authenticator using`
- The link to the configuration page [here](https://docs-staging.secretless.io/Latest/en/Content/Get%20Started/using-dap.htm#OpenShiftvsKubernetes) is using `MadCap:xref` and dropping the correct display text, and is instead showing the default display text which includes the `Secreteless` typo
- The [Assumptions](https://docs-staging.secretless.io/Latest/en/Content/Get%20Started/using-dap.htm#Assumptions) section includes two links that use the `MadCap:xref` default text instead of the expected link text

Things fixed in https://github.com/cyberark/secretless-docs/pull/166/files:
- There is a markdown code snippet [here](https://docs-staging.secretless.io/Latest/en/Content/Get%20Started/using-dap.htm#RequiredInformation) that needs to be converted to HTML
- The header for [this section](https://docs-staging.secretless.io/Latest/en/Content/Get%20Started/using-dap.htm#AddtheSecretlesstoyourappdeploymentmanifest) says `Add the Secretless`

@apotterri can you please clarify the issue you saw here - it's not obvious to me from the image: 
![sixth.png](https://images.zenhubusercontent.com/5c9d0367270ed03f5cb98c7e/a845ce02-6edc-4d06-b0ac-4d769831ae99)

The only other item was this one, which is already in cyberark/secretless-docs#165 (though I added the screenshot to the issue):
![third.png](https://images.zenhubusercontent.com/5c9d0367270ed03f5cb98c7e/d4804a38-4cc4-4225-91d7-82d511e809b8)

**Comment by izgeri** [comment]
I also added this issue, which I think could help make it easier to track all of the variables in the DAP guide: cyberark/secretless-docs#167

**Comment by apotterri** [comment]
This says you're configuring the "database" to connect to `localhost:5432`, but you're configuring the *client* to connect to Secretless.

> @apotterri can you please clarify the issue you saw here - it's not obvious to me from the image:
> ![sixth.png](https://camo.githubusercontent.com/0a75b1f4e5b094341b0e2de87171c61b9cfff844/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3563396430333637323730656430336635636239386337652f61383435636530322d366564632d346430362d623061632d346437363938333161653939)
