### ISSUE TITLE
Add additional performance test scenarios to test app

### ISSUE THREAD

**Issue by izgeri** [cyberark/secretless-broker#734]
Related to #725

Augment the test app that we're using to exercise Secretless to test these additional use cases:

- Secretless is stable
  - It can consistently open connections while running
    - [ ] You can continue to open connections and run queries
- [ ] Secretless performs under load in a realistic environment

**Comment by sgnn7** [comment]
PR: https://github.com/cyberark/secretless-broker/pull/739
