### ISSUE TITLE
Plugin interface is moved to internal until refactor

### ISSUE THREAD

**Issue by izgeri** [cyberark/secretless-broker#767]
We initially defined a plugin interface, but it was early in the life of the project and we've come to understand the system more since then. We are in the planning phases of a project to refactor the plugin interface (#693) but until then we want to remove the plugin interface from the public API.

AC:
- [x] Plugin interface removed from the public API and moved to `internal/`
- [x] Plugin documentation removed from the public website (eg remove the link from `docs/_data/navigation.yml`)
- [x] Update example plugin tests as needed (including turning them off / moving to `manual/` for the time being, if appropriate)
- [x] Update plugin [README](https://github.com/cyberark/secretless-broker/tree/master/pkg/secretless/plugin) to clearly indicate the state of the package (eg internal only, pieces may move to external over time)

**Comment by jonahx** [comment]
Relevant PR:

https://github.com/cyberark/secretless-broker/pull/769
