### ISSUE TITLE
Adding troubleshooting for secretless version that doesn’t support v2 config

### ISSUE THREAD

**Issue by doodlesbykumbi** [cyberark/secretless-broker#775]
**Is your feature request related to a problem? Please describe.**
The error below is perplexing if you're a user without the context of Secretless configuration versions and their implementation. It would be helpful to have such entries in the troubleshooting.

```
2019/07/01 12:42:28 Trying to load configuration file: /etc/secretless/secretless.yml
2019/07/01 12:42:28 Failed to initialize configuration manager 'configfile': Unable to parse configuration: 'yaml: unmarshal errors:
  line 1: field version not found in type config.Config
  line 3: field services not found in type config.Config'
```
**Describe the solution you'd like**
A section in the troubleshoot guide with 
1. examples of telltale signs of stale versions of Secretless without v2 support
2. steps to address the issue such as using `imagePullPolicy: latest` and reschedule the running pods in Kubernetes

**Describe alternatives you've considered**
~A clear and concise description of any alternative solutions or features you've considered.~

**Additional context**
~Add any other context or screenshots about the feature request here.~

**Comment by izgeri** [comment]
Moving to https://github.com/cyberark/secretless-docs/issues/172
