### ISSUE TITLE
Dependencies are cleaned up

### ISSUE THREAD

**Issue by izgeri** [cyberark/secretless-broker#785]
We have several dependencies in go.mod that we don't directly use in our code, and these should be cleaned up if possible. In particular:

- Do we need `gopkg.in/yaml.v1`?
- Are there any `hashicorp` deps that we can clean up? There’s a bunch in go.mod but we only seem to directly import `github.com/hashicorp/vault`
- Do we need `github.com/jefferai/jsonx`? I don’t see it imported anywhere, but it’s in go.mod.

**Comment by sgnn7** [comment]
```
$ go mod why github.com/jefferai/jsonx
...
# github.com/jefferai/jsonx
github.com/cyberark/secretless-broker/internal/app/secretless/providers/vault
github.com/hashicorp/vault/api
github.com/hashicorp/vault/api.test
github.com/hashicorp/vault/audit
github.com/jefferai/jsonx
```

jsonx is an indirect dependency of the vault API modules so it's needed

**Comment by sgnn7** [comment]
`gopkg.in/yaml.v1` is imported through summon CLI with `github.com/cyberark/summon/secretsyml` package. We'd need to upgrade summon repo or copy over the needed files and upgrade here.

**Comment by sgnn7** [comment]
I might be able to clean up hashi deps in go.mod by pointing to a submodule instead of module so I'll give that a try

**Comment by sgnn7** [comment]
PR for hashi cleanup: https://github.com/cyberark/secretless-broker/pull/787
