### ISSUE TITLE
Instructions for deploying Secretless with Conjur OSS are available

### ISSUE THREAD

**Issue by izgeri** [cyberark/secretless-broker#790]
We want to create a `Using Conjur OSS` guide like our [Using DAP guide](https://docs.secretless.io/Latest/en/Content/Get%20Started/using-dap.htm), so we need to manually verify and document the instructions.

AC:
- The instructions should assume the user is deploying to Kubernetes
- The instructions should include a [Prerequisites](https://docs.secretless.io/Latest/en/Content/Get%20Started/using-dap.htm#Prerequisites) section that describes the assumptions (e.g. Conjur OSS is already deployed to Kubernetes and configured to use the Kubernetes authenticator with the helm chart) and the required information (eg the variables you need to know to fill in the rest of the data)
- The instructions should include whatever additional steps are needed to deploy an app to Kubernetes with Secretless broker, and whenever possible should mirror the structure in the DAP guide

Once complete, a link to the instructions (as a gist, Word doc, or whatever other format you prefer) should be attached to this issue, and a comment should be added to cyberark/secretless-docs#177 so that formal documentation may be created from it.

**Comment by doodlesbykumbi** [comment]
Instructions available at https://github.com/cyberark/secretless-broker/blob/conjur-oss-demo/demos/conjur-oss/INSTRUCTIONS.md
