### ISSUE TITLE
Spike: Prove out and implement basic parts of the e2e test harness

### ISSUE THREAD

**Issue by sgnn7** [cyberark/secretless-broker#827]
We have a number of things to prove out and explore in the E2E design doc that don't have almost any "needs changing" feedback which we can start on and try out before the document has a sign off.

AC - all optional:
- [x] Create repo for holding e2e test code
- [x] There is a barebones cucumber test suite (single demo test)
- [x] Cucumber can output results to a Jenkins-parsable file
- [ ] Test suite can start and stop services (no lifecycle handling)
- [ ] Test suite can invoke services based on service-definitions (single demo test)
- [ ] Test suite can manage lifecycles of stated services (single demo test)
- [ ] Test suite can apply service configs (single demo test)

**Comment by sgnn7** [comment]
WIP branch: https://github.com/conjurinc/secretless-broker-e2e-tests/compare/add-lifecycle-handling?expand=1

Addition of lifecycle handling for services encountered a much trickier set of problems/questions than anticipated:
- Will startup scripts use background/oneshot scripts or foreground ones? We will need a radically different lifecycle management for those two options.
- Getting stdout/stderr under different type of service invocations (background/foreground) and different exit status codes turns out to be highly problematic given that Popen3 returns io pipes that provide mostly blocking API and non-blocking api seems like it would be both complex and cpu-intensive
- Questions on how to notify user of problems and when to display output from those services in the console is under question
- What happens when a foreground service doesn't immediately respond to SIGKILL? Do we wait for test exit, do we block `x` seconds and SIGTERM? All solutions here are complex.

There's probably a few more questions/problems but these are the big ones.

**Comment by doodlesbykumbi** [comment]
@sgnn7 We really want the service implementation to handle the start and the stop, without interference. If it (the service implementation) needs to keep track of PIDs etc. then it should do that. Imagine running something on Kubernetes.

The lifecycle management responsibilities of our testing framework are to run `start_service` and to run `stop_service` at a prescribe point or automagically at the end of the test case regardless of the outcome.

**Comment by sgnn7** [comment]
@doodlesbykumbi What are the edge case behaviors that you're thinking of here?
- When does the start service script return? when the service is launched or ready?
- Does error in start require the service to be stopped?
- What does the start wrapper pass back to caller and when (success/failure x stdout/stderr)?

**Comment by sgnn7** [comment]
PS: Regardless of where we do lifecycle management though, I think we'll still have to deal with tricky process management code it's just that it will either be in the test runner or instance runner scripts

**Comment by doodlesbykumbi** [comment]
@sgnn7 
The start script returns connector details or whatever information makes sense for the test steps to follow. For example, Conjur should return CONJUR_ACCOUNT, CONJUR_APPLIANCE_URL etc. This information is returned as JSON. It should be written by the start script to a path provided as an argument to the start_script. This is why a FIFO might be useful.

The service script knows best when it is "ready". It will only write to the output JSON file when it is ready. The output file is 100% not stdout or stderr so that the start scripts can have full reign to use those as a normal process would, no unnecessary constraints.

An error is start means a failed test
