### ISSUE TITLE
ProxyService interface is designed and created

### ISSUE THREAD

**Issue by jonahx** [cyberark/secretless-broker#844]
## Description

This will be the new, simpler interface for (essentially) what are now Listeners.  It will likely have only 2-3 methods

The proxy service interface should be responsible for every common thing that the current listener interface is responsible for as well as the streaming functionality that currently lives in some of the existing handlers

Elements of the existing listener interface that are specific to given listeners will be part of the implementation of the proxyservice interface for the given type (eg tcp, http, ssh)

AC:
- [ ] Create the interface
- [ ] Create the `proxyservice` interface

**Comment by izgeri** [comment]
Note: we may later want to even further simplify what's in this interface beyond what we define in this first iteration - but in this first pass, the key is figuring out what common functionality from the old listeners / handler-streaming belongs in a proxy service whose job is to be responsible for receiving incoming requests, directing them to the appropriate connector, and streaming the connection from there as needed
