### ISSUE TITLE
Design `ActiveServices` Interface 

### ISSUE THREAD

**Issue by jonahx** [cyberark/secretless-broker#845]
## Description

The interface name may change during design, but this will take the `v2.config` and a list of all plugins (from `AllAvailablePlugins` defined in #878), and return instances of all `ProxyService` instances that need to be started (it instantiates the objects but doesn't call the `Run` method on them).  The code in #853 will be written to invoke `ActiveServices` to get the list of proxy services to start and then actually start them.

This may be just a simple function.  TBD during design. 

AC:
- [ ] The final `ActiveServices` Interface or function signature.
- [ ] There is a test for activeservice to ensure that only http connectors are allowed to listen on the same socket

**Comment by jonahx** [comment]
I think we will not be needing this as a separate interface after all.   The logic will exist in `Secretless`.

**Comment by izgeri** [comment]
Should this issue be closed?
