### ISSUE TITLE
Connector plugin interface has docs in repo

### ISSUE THREAD

**Issue by jonahx** [cyberark/secretless-broker#847]
## Description

This will be as simple as copying over the README and adding a link to it in the godoc (eg a `doc.go` file in the `plugin.connector` package)

AC:
- [x] Connector plugin package has README with same content as current PLUGIN_README
- [x] Connector plugin package has godoc linking to README
- [x] Godoc has been viewed using local server and formatting looks good
- [x] The [CONTRIBUTING plugin section](https://github.com/cyberark/secretless-broker/blob/master/CONTRIBUTING.md#plugins) is updated with accurate info
- TW has reviewed the content (completed in cyberark/secretless-docs#204)

**Comment by izgeri** [comment]
Closing, since we defer any godoc updates until we have formal doc updates that we can link to
