### ISSUE TITLE
Create SSH Agent ProxyService

### ISSUE THREAD

**Issue by jonahx** [cyberark/secretless-broker#851]
## Description

This will be translation of what is currently the SSH Listener, and may include parts of the SSH Handler.

- [x] Current sshagent.Listener fully removed.
- [x] SSH Agent `ProxyService` exists in `proxyservice.sshagent` package.

This PR for the TCPProxyService:

https://github.com/cyberark/secretless-broker/pull/890

can be used as a template for both the code and, more importantly, the unit tests.

**Comment by izgeri** [comment]
@jonahx is this needed? why can't this use the same proxy service as ssh?
