### ISSUE TITLE
Secretless stability tests have been rerun

### ISSUE THREAD

**Issue by jonahx** [cyberark/secretless-broker#864]
AC:
- [ ] Performance metrics of the new implementation are gathered (TBD)

Data output (prelim):
- https://gist.github.com/sgnn7/f4e961dc5cca272cfd25aa30d7fe7558

Plan (10thread):
- [x] 1hr/PG/norecreate/1thread ->
- [x] 1hr/MySQL/norecreate1thread ->
- [ ] 1hr/PG/recreate ->
- [ ] 1hr/MySQL/recreate ->
- [ ] 4day/PG/norecreate/10threads ->
- [ ] 4day/MySQL/norecreate/10threads ->
- …

**Comment by izgeri** [comment]
Note: in the last stable release 1.0.0 we had the following metrics:
- On persistent connections, 2 query errors in over ~10billion queries, effectively being a ten 9's uptime.
- On recreated connections, 100ms interval during rotation (1 per 3 days if using standard settings) where a query may fail but can recover immediately after. Datapoints > ~10 million. Effectively we are at > six 9s uptime.

- we found that 90% of pg connections had query performance within 10% of direct-to-db
and 89.26% of mysql connections had query performance within 15% of direct-to-db
so, almost 90%
- by “may fail but can recover immediately after” we mean literally the next connection attempt is successful
- for pg,  96% of queries were within 20% of direct-to-db
- for mysql, ~92% of queries were within 20% of direct-to-db

**Comment by izgeri** [comment]
In v1.2.0 (single threaded runs for 1 hr):
- ~87% of pg connections had a query performance within 10% of direct-to-db and ~86% of mysql connections had a query performance within 15% of direct-to-db
- for pg, 94% of queries were within 20% of direct-to-db
- for mysql, ~90% of queries were within 20% of direct-to-db
