### ISSUE TITLE
AllAvailablePlugins type interface is implemented

### ISSUE THREAD

**Issue by jonahx** [cyberark/secretless-broker#878]
- Write independently testable function `func ExternalPlugins(dir) AvailablePlugins`
- Similarly: `InternalPlugins() AvailablePlugins`
- And, for use by `Secretless`: `InternalPlugins(externalPluginDir) AvailablePlugins` which combines the two.

AC:
~- [ ] Verify and then create interface above~
~- [ ] Verify this can still work with gRPC~
- [ ] `AvailablePlugins` interface is implemented

**Comment by izgeri** [comment]
this effort will create the one bit of code that knows
- where plugins are located
- how to load them
- have them all loaded up and indexed by name into the HTTPPlugin and TCPPlugin maps as the output

it uses info about what's statically available in the filesystem to generate an object that lists available connector plugins, but doesn't actually instantiate them

in another bit of code all of the proxyservices are actually instantiated based on secretless.yml

**Comment by izgeri** [comment]
@sgnn7 just to note in #845 the data in this will be used with the config to determine which services should be active in secretless

**Comment by sgnn7** [comment]
WIP branch is here: https://github.com/cyberark/secretless-broker/compare/883-allavailableplugins-interface?expand=1. Moving back to defined.
