### ISSUE TITLE
Support ability to use unix domain listeners again

### ISSUE THREAD

**Issue by sgnn7** [cyberark/secretless-broker#918]
Currently, unix domain sockets are not supported as listening targets.

AC:
- [ ] Listeners can accept and use `unix://`-prefixed listening targets

**Comment by porjo** [comment]
I'm confused by this. Documentation here shows an example using unix sockets: https://docs.secretless.io/Latest/en/Content/References/connectors/mysql.htm

I've tested this with v1.1.0 and it worked fine.

**Comment by sgnn7** [comment]
@porjo We're in the middle of a big refactor with lots of breaking changes and what you see available in the default views is vastly different what currently being worked on. 

Specifically:
- Current stable release is [`v1.1.0`](https://github.com/cyberark/secretless-broker/releases/tag/v1.1.0) . This release version matches documented capabilities.
- Current default branch is [`latest`](https://github.com/cyberark/secretless-broker/tree/latest). This code matches documented capabilities.
- Current development effort is actually on [`master`](https://github.com/cyberark/secretless-broker/tree/master) branch. No documentation yet and lots of things are needing to be re-implemented from our side to reach feature parity with v1.1.0. If you notice, we are currently about 130 commits ahead of master on that branch.

Because of this, you will probably see more "weird" issues filed that seem to not correlate with the released product features for a while but it's mostly due to the fact that we are working on implementing better (but also breaking) plugin APIs and improved project code structure.

Let me know if that answers your question and I'll see about maybe getting our team to add some label or prefix to these "next-gen" release issues to avoid the confusion.

CC: @izgeri for that last paragraph

**Comment by porjo** [comment]
Ah, ok - sorry for the noise. So I should look for the 'Secretless Connector Plugin Interface' milestone to know if the issue is for code in active development?

**Comment by izgeri** [comment]
@porjo - yes, exactly :) we should be cutting a prerelease with the bulk of those changes within a week, and flipping the default branch back to master.
