### ISSUE TITLE
MySQL sslmode: verify-full not working

### ISSUE THREAD

**Issue by porjo** [cyberark/secretless-broker#922]
## Summary
Attempting to use `verify-full` (or `verify-identity`) as the `sslmode` config parameter results in error for the client

## Steps to Reproduce
1. Run secretless-broker with MySQL config that specifies `sslmode: verify-full`
2. Connect with mysql client: `mysql -h 127.0.0.1`

## Expected Results
The connection should either work without error when the name matches, or error when the name does not match with a descriptive error. secretless-broker should output some info to console.

## Actual Results (including error logs, if applicable)
The connection fails with:

```
ERROR 2013 (HY000): Lost connection to MySQL server at 'reading authorization packet', system error: 0
```
This happens regardless of whether or not the server name matches the SSL certificate CN. secretless-broker does not output any error to console. 

Switching back to `verify-ca` works fine.

## Additional Information
MySQL server is AWS RDS instance, running version: 5.6.10 

secretless-broker config file:
```yaml
version: "2"
services:
  mysql_tcp:
    protocol: mysql
    listenOn: tcp://0.0.0.0:3306
    credentials:
      host: devdb1
      port: 3306
      username: webaccess
      password:
        from: aws
        get: MYSQL_WEBACCESS_PASSWORD
      sslmode: verify-full
      sslrootcert:
        from: file
        get: rds-combined-ca-bundle.pem
```

secretless-broker console output:
```
# AWS_REGION=ap-southeast-2 ./secretless-broker 
2019/10/01 06:25:24 Secretless v1.1.0-7f978b3 starting up...
2019/10/01 06:25:24 Loading internal plugins...
2019/10/01 06:25:24 - ConfigurationManagers: [k8s/crd configfile]
2019/10/01 06:25:24 - ConnectionManagers: []
2019/10/01 06:25:24 - Providers: [env file keychain kubernetes literal vault aws conjur]
2019/10/01 06:25:24 - Handlers: [ssh sshagent http/aws http/basic_auth http/conjur mysql pg]
2019/10/01 06:25:24 - Listeners: [pg ssh ssh-agent http mysql]
2019/10/01 06:25:24 Completed loading internal plugins.
2019/10/01 06:25:24 Loading external library plugins...
2019/10/01 06:25:24 open /usr/local/lib/secretless: no such file or directory
2019/10/01 06:25:24 Registering shutdown signal listeners...
2019/10/01 06:25:24 Initializing configuration manager 'configfile'...
2019/10/01 06:25:24 Trying to load ./secretless.yml...
2019/10/01 06:25:24 Configuration file ./secretless.yml loaded
2019/10/01 06:25:24 Configuration manager 'configfile' initialized (configSpec: '').
2019/10/01 06:25:24 Initializing connection managers...
2019/10/01 06:25:24 Initialization of plugins done.
2019/10/01 06:25:24 Initializing the proxy...
2019/10/01 06:25:24 Initializing health check on :5335...
2019/10/01 06:25:24 Initialization of health check done. You can access the endpoint at `/live` and `/ready`.
2019/10/01 06:25:24 Waiting for valid configuration to be provided...
2019/10/01 06:25:24 Configuration manager 'configfile' provided new configuration...
2019/10/01 06:25:24 Reloading...
2019/10/01 06:25:24 ----------------------------
2019/10/01 06:25:24 Registering reload signal listeners...
2019/10/01 06:25:24 Starting all listeners and handlers...
2019/10/01 06:25:24 mysql listener 'mysql_tcp' listening at: [::]:3306
2019/10/01 06:25:29 Instantiating provider 'literal'
2019/10/01 06:25:29 Instantiating provider 'aws'
2019/10/01 06:25:29 Instantiating provider 'file'
```

**Comment by izgeri** [comment]
@porjo thanks for logging this! At current, the MySQL connector only supports the `disable`, `require`, and `verify-ca` SSL modes.

There is an open issue (https://github.com/cyberark/secretless-broker/issues/548) for adding support for `verify-full`. If this is something you'd like to use, I can look into a timeline for when we would add this support. We are also open to [contributions](https://github.com/cyberark/secretless-broker/blob/latest/CONTRIBUTING.md).

Apologies for the delay in responding to your request!

**Comment by izgeri** [comment]
Let's move any further conversation to #548 :)

**Comment by izgeri** [comment]
One more note @porjo - I looked over our docs and I can see we refer to `verify-full` a couple of times on the MySQL page. I've put in a request to update this to be more clear about the modes we don't yet support so that hopefully others don't run into this same issue in the future.
