### ISSUE TITLE
Secretless-broker 1.2.x is XAd

### ISSUE THREAD

**Issue by sgnn7** [cyberark/secretless-broker#962]
AC:
- [ ] Performance metrics of the new implementation are gathered (TBD)

Data output (prelim):
- https://gist.github.com/sgnn7/f4e961dc5cca272cfd25aa30d7fe7558

**Comment by sgnn7** [comment]
Plan (10thread):
- [ ] 6hr/PG/norecreate ->
- [ ] 6hr/MySQLl/norecreate ->
- [ ] 6hr/PG/recreate ->
- [ ] 6hr/MySQL/recreate ->
- [ ] 4day/PG/norecreate ->
- [ ] 4day/MySQL/norecreate ->
- …

**Comment by izgeri** [comment]
@sgnn7 is this a duplicate of #864?

**Comment by sgnn7** [comment]
Seems like it though this one has more details at this point

**Comment by izgeri** [comment]
it's not a lot, though. I'll copy it over and close this issue.
